# Generated by Django 5.2.3 on 2025-06-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
